### ISSUE TITLE
Cant use helper functions in Nova

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [outl1ne/nova-page-manager#72] opened 2021-03-16 05:16 UTC
Im trying to use the `nova_get_regions()` helper function within Nova itself, so I can pull in some region data and display it in a Field

For some reason this causes some kind of infinite loop, hang or crash? The page just times out. Is there a way I can access region or page data within Nova without this happening?

**Comment by KasparRosin** [comment] 2021-04-19 09:34
Hey @matthewjumpsoffbuildings 

I was unable to reproduce the issue with my nova. Could you provide more information/reproducible code example so we can take another look at this issue.

**Comment by matthewjumpsoffbuildings** [comment] 2021-04-19 09:44
In one of my Templates, I had a static function `regions()` which simply called `nova_get_regions()` and returned that as an associative array. Then in my Field definitions I was trying to use some of the data from that (some colors set in a different region), to prefill the palette of a Color field.

**Comment by KasparRosin** [comment] 2021-04-19 10:11
```
$regions = nova_get_regions();
$titles = collect($regions)->pluck('data')->pluck('et.title')->filter();
 return [
     Select::make('Titles')->options($titles),
]
```

I tried to reproduce the issue with code above but was unable to. 
Could be an issue with the colour field/invalid data.

Closing this at the moment since i can't find a reason how this could be regions/page-manager issue.

**Comment by matthewjumpsoffbuildings** [comment] 2021-04-19 11:01
It didn't matter if I actually implemented the retrieved values into the Color Field (or any other field). The mere presence of the  `nova_get_regions()` in my Template was enough to crash the app.

I was actually caching the response of `nova_get_regions()` using Laravels `Cache` helper? Could that be the source of the issue?

Heres a rough example
```php
class AppController extends Controller
{
	public static function regions()
	{
		return Cache::remember('regions', 60, function(){
			return nova_get_regions();
		});
	}
```

My Template
```php
class Shortlist extends Template
{
	public static $type = 'region';
	public static $name = 'Shortlist';

	public function fields(Request $request): array
	{
		$regions = AppController::regions();
		return [ ...
```

Even if I do nothing with `$regions`, just having the call to `nova_get_regions()` in the static function in `AppController` is enough to break it

**Comment by KasparRosin** [comment] 2021-04-19 13:08
My bad, this seems to be the problem indeed when calling nova_get_regions inside region template. 
I was testing this inside a page template, which was the reason why i wasn't able to reproduce.

**Comment by matthewjumpsoffbuildings** [comment] 2021-04-19 13:12
No worries. Right now Im getting around it by just using the `Region::all()` method to get all the regions data, that doesn't crash anything, though the data is formatted a bit differently than it would be from `nova_get_regions()`

**Closed as completed** 2021-09-02 15:10 UTC
